
CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
	"sess" json NOT NULL,
	"expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;

CREATE OR REPLACE FUNCTION from_timestamp_ms(t TIMESTAMPTZ) RETURNS FLOAT AS $$
  BEGIN
    RETURN EXTRACT(EPOCH FROM t) * 1000.0;
  END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION to_timestamp_ms(t FLOAT) RETURNS TIMESTAMPTZ AS $$
  BEGIN
    RETURN to_timestamp(t / 1000.0);
  END;
$$ LANGUAGE plpgsql;

CREATE TABLE releases_cache (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT 39,
  releases JSON NOT NULL,
  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT only_one_row CHECK (id = 39)
);

CREATE TABLE users (
  id UUID PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  admin BOOLEAN NOT NULL DEFAULT FALSE,
  confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  confirm_token TEXT,

  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assets (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  file TEXT NOT NULL,
  thumbnail TEXT NOT NULL,
  creator UUID REFERENCES users(id),
  category TEXT NOT NULL,
  subcategory TEXT NOT NULL,

  created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
